"use client";

import { useEffect, useRef, useState } from "react";
import { Loader2, Sparkles, ListChecks, Gauge, ShieldAlert, ChevronDown, Network, GitBranch, Database } from "lucide-react";
import { handleSpotlight } from "@/lib/uiEffects";

interface SecurityFinding {
  filePath: string;
  line: number;
  ruleId: string;
  description: string;
  snippet: string;
}

interface RepoProfile {
  architectureDiagram: string;
  flowDiagram: string;
  erDiagram: string;
  onboarding: string[];
  complexity: {
    estimateWeeks: number;
    confidence: "low" | "medium" | "high";
    breakdown: { frontend: string; backend: string; devops: string };
  };
}

const CONFIDENCE_COLOR: Record<string, string> = {
  low: "text-red-300 bg-red-400/10",
  medium: "text-amber-300 bg-amber-400/10",
  high: "text-emerald-300 bg-emerald-400/10",
};

function MermaidDiagram({ chart }: { chart: string }) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const mermaid = (await import("mermaid")).default;
        mermaid.initialize({ startOnLoad: false, theme: "dark", securityLevel: "strict" });
        const id = `mermaid-${Math.random().toString(36).slice(2)}`;
        const { svg } = await mermaid.render(id, chart);
        if (!cancelled && containerRef.current) containerRef.current.innerHTML = svg;
      } catch (err: any) {
        if (!cancelled) setError(err.message ?? "Could not render diagram");
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [chart]);

  if (error) {
    return <p className="text-xs text-red-300/80">Diagram render failed: {error}</p>;
  }
  return <div ref={containerRef} className="overflow-x-auto [&_svg]:mx-auto" />;
}

type DiagramTab = "architecture" | "flow" | "data";

export default function RepoProfilePanel({
  repositoryId,
  apiKey,
  securityFindings,
}: {
  repositoryId: string;
  apiKey: string;
  securityFindings: SecurityFinding[];
}) {
  const [open, setOpen] = useState(false);
  const [profile, setProfile] = useState<RepoProfile | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [diagramTab, setDiagramTab] = useState<DiagramTab>("architecture");
  const [justAutoGenerated, setJustAutoGenerated] = useState(false);

  async function generate(force = false) {
    if (!apiKey.trim()) return;
    setLoading(true);
    setError("");
    try {
      const res = await fetch("/api/profile", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ repositoryId, apiKey, force }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Failed to generate overview");
      setProfile(data.profile);
      return true;
    } catch (err: any) {
      setError(err.message ?? "Something went wrong");
      return false;
    } finally {
      setLoading(false);
    }
  }

  // Auto-generate diagrams the moment a repo is ingested and a key is already present —
  // no manual click needed. If the key arrives later (pasted after ingesting), this fires
  // once it does. Guarded on `error` too so a failed attempt doesn't retry-loop.
  useEffect(() => {
    setProfile(null);
    setError("");
    setDiagramTab("architecture");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [repositoryId]);

  useEffect(() => {
    if (profile || loading || error || !apiKey.trim()) return;
    (async () => {
      const ok = await generate(false);
      if (ok) {
        setOpen(true);
        setJustAutoGenerated(true);
        window.setTimeout(() => setJustAutoGenerated(false), 2000);
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [repositoryId, apiKey]);

  const diagrams: { key: DiagramTab; label: string; icon: typeof Network; chart?: string }[] = profile
    ? [
        { key: "architecture", label: "Architecture", icon: Network, chart: profile.architectureDiagram },
        { key: "flow", label: "Flow", icon: GitBranch, chart: profile.flowDiagram },
        ...(profile.erDiagram ? [{ key: "data" as const, label: "Data model", icon: Database, chart: profile.erDiagram }] : []),
      ]
    : [];

  return (
    <section
      className={`spotlight-card rounded-2xl border bg-white/[0.03] shadow-xl backdrop-blur-sm transition ${
        justAutoGenerated ? "border-fuchsia-400/40" : "border-white/10"
      }`}
      onMouseMove={handleSpotlight}
    >
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="flex w-full items-center justify-between px-5 py-4 text-left"
      >
        <span className="flex items-center gap-2 text-sm font-medium text-white/80">
          <Sparkles className="h-4 w-4 text-indigo-300" />
          Repo Overview
          {loading && !open && (
            <span className="flex items-center gap-1 rounded-full bg-white/5 px-2 py-0.5 text-[11px] text-white/40">
              <Loader2 className="h-2.5 w-2.5 animate-spin" /> generating…
            </span>
          )}
          {profile && !open && !loading && (
            <span className="pop-in rounded-full bg-emerald-400/15 px-2 py-0.5 text-[11px] text-emerald-300">Ready</span>
          )}
          {securityFindings.length > 0 && (
            <span className="rounded-full bg-red-400/15 px-2 py-0.5 text-[11px] text-red-300">
              {securityFindings.length} security finding{securityFindings.length === 1 ? "" : "s"}
            </span>
          )}
        </span>
        <ChevronDown className={`h-4 w-4 text-white/40 transition-transform ${open ? "rotate-180" : ""}`} />
      </button>

      {open && (
        <div className="space-y-5 border-t border-white/10 px-5 py-5">
          {securityFindings.length > 0 && (
            <div className="space-y-2">
              <p className="flex items-center gap-1.5 text-xs font-medium text-red-300">
                <ShieldAlert className="h-3.5 w-3.5" /> Potential secrets found
              </p>
              <ul className="space-y-1.5">
                {securityFindings.map((f, i) => (
                  <li key={i} className="rounded-lg border border-red-400/20 bg-red-400/5 px-3 py-2 text-xs">
                    <div className="text-red-300/90">{f.description}</div>
                    <div className="mt-0.5 font-mono text-[11px] text-white/40">
                      {f.filePath}#L{f.line}
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {!profile && (
            <button
              type="button"
              onClick={() => generate(false)}
              disabled={loading || !apiKey.trim()}
              className="flex items-center gap-2 rounded-xl bg-indigo-500 px-4 py-2 text-sm font-medium text-white transition hover:bg-indigo-400 disabled:cursor-not-allowed disabled:opacity-40"
            >
              {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
              {loading ? "Generating…" : "Generate architecture, flow & data diagrams"}
            </button>
          )}
          {!apiKey.trim() && !profile && (
            <p className="text-xs text-white/30">Add your LLM API key above first — diagrams generate automatically once it's there.</p>
          )}
          {error && <p className="text-xs text-red-300/90">{error}</p>}

          {profile && (
            <div className="space-y-6">
              <div>
                <div className="mb-2 flex items-center gap-1 rounded-xl border border-white/10 bg-black/20 p-1">
                  {diagrams.map(({ key, label, icon: Icon }) => (
                    <button
                      key={key}
                      type="button"
                      onClick={() => setDiagramTab(key)}
                      className={`flex flex-1 items-center justify-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium transition ${
                        diagramTab === key ? "bg-indigo-500 text-white shadow-sm" : "text-white/40 hover:text-white/70"
                      }`}
                    >
                      <Icon className="h-3.5 w-3.5" />
                      {label}
                    </button>
                  ))}
                </div>
                <div className="rounded-lg border border-white/10 bg-black/20 p-4">
                  {diagrams
                    .filter((d) => d.key === diagramTab)
                    .map((d) => <MermaidDiagram key={d.key} chart={d.chart!} />)}
                </div>
              </div>

              <div>
                <h3 className="mb-2 flex items-center gap-1.5 text-xs font-medium uppercase tracking-wide text-white/40">
                  <ListChecks className="h-3.5 w-3.5" /> Onboarding checklist
                </h3>
                <ol className="space-y-1.5">
                  {profile.onboarding.map((step, i) => (
                    <li key={i} className="flex gap-2 text-sm text-white/80">
                      <span className="text-indigo-300/70">{i + 1}.</span>
                      {step}
                    </li>
                  ))}
                </ol>
              </div>

              <div>
                <h3 className="mb-2 flex items-center gap-1.5 text-xs font-medium uppercase tracking-wide text-white/40">
                  <Gauge className="h-3.5 w-3.5" /> Complexity estimate
                </h3>
                <div className="flex flex-wrap items-center gap-2 text-sm">
                  <span className="text-white/90">~{profile.complexity.estimateWeeks} dev-weeks</span>
                  <span className={`rounded-full px-2 py-0.5 text-[11px] ${CONFIDENCE_COLOR[profile.complexity.confidence]}`}>
                    {profile.complexity.confidence} confidence
                  </span>
                </div>
                <div className="mt-2 grid grid-cols-1 gap-1.5 text-xs text-white/50 sm:grid-cols-3">
                  <div><span className="text-white/30">Frontend: </span>{profile.complexity.breakdown.frontend}</div>
                  <div><span className="text-white/30">Backend: </span>{profile.complexity.breakdown.backend}</div>
                  <div><span className="text-white/30">DevOps: </span>{profile.complexity.breakdown.devops}</div>
                </div>
              </div>

              <button
                type="button"
                onClick={() => generate(true)}
                disabled={loading}
                className="text-xs text-white/40 underline underline-offset-2 hover:text-white/70 disabled:opacity-40"
              >
                {loading ? "Regenerating…" : "Regenerate"}
              </button>
            </div>
          )}
        </div>
      )}
    </section>
  );
}
