"use client";

import { useEffect, useState } from "react";
import { Loader2, FileCode2, Sparkles } from "lucide-react";
import Markdown, { CodeBlock, type CitationRef } from "@/components/Markdown";

// Public, read-only view of one shared Q&A turn (see /api/share) — no API key, no ingestion,
// no auth needed to view: it's just the stored question/answer/citations rendered back out.

interface SharedAnswer {
  repoFullName: string;
  question: string;
  answer: string;
  citations: CitationRef[];
  mode: string;
  createdAt: string;
}

export default function SharedAnswerView({ id }: { id: string }) {
  const [data, setData] = useState<SharedAnswer | null>(null);
  const [error, setError] = useState("");
  const [expanded, setExpanded] = useState<Set<number>>(new Set());

  useEffect(() => {
    (async () => {
      try {
        const res = await fetch(`/api/share/${id}`);
        const json = await res.json();
        if (!res.ok) throw new Error(json.error ?? "Failed to load this shared answer");
        setData(json);
      } catch (err: any) {
        setError(err.message ?? "Something went wrong");
      }
    })();
  }, [id]);

  function toggle(i: number) {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(i)) next.delete(i);
      else next.add(i);
      return next;
    });
  }

  return (
    <main className="mx-auto flex min-h-screen max-w-2xl flex-col justify-center px-4 py-12">
      <div className="mb-6 flex items-center gap-2 text-sm text-white/50">
        <Sparkles className="h-4 w-4 text-indigo-300" />
        <span className="font-semibold text-white/80">RepoMind</span>
        <span>· shared answer</span>
      </div>

      {error && <p className="glass-panel rounded-2xl p-5 text-sm text-red-300/90">{error}</p>}

      {!error && !data && (
        <div className="glass-panel flex items-center gap-2 rounded-2xl p-5 text-sm text-white/40">
          <Loader2 className="h-4 w-4 animate-spin" /> Loading…
        </div>
      )}

      {data && (
        <div className="glass-panel spotlight-card rounded-2xl p-6">
          <p className="mb-1 font-mono text-xs text-white/30">{data.repoFullName}</p>
          <h1 className="mb-4 text-lg font-medium text-white/90">{data.question}</h1>
          <div className="rounded-lg border border-white/10 bg-white/[0.04] px-4 py-3 text-sm text-white/90">
            <Markdown text={data.answer} citations={data.citations} />
          </div>

          {data.citations.length > 0 && (
            <div className="mt-3 flex flex-wrap gap-1.5">
              {data.citations.map((c, j) => (
                <button
                  key={j}
                  id={`citation-0-${j + 1}`}
                  type="button"
                  onClick={() => toggle(j)}
                  className={`inline-flex items-center gap-1 rounded-md border px-2 py-0.5 font-mono text-[11px] transition-colors ${
                    expanded.has(j)
                      ? "border-fuchsia-400/40 bg-fuchsia-400/10 text-fuchsia-200"
                      : "border-white/10 bg-black/20 text-white/50 hover:border-fuchsia-400/30 hover:text-white/80"
                  }`}
                >
                  <FileCode2 className="h-3 w-3" />
                  <span className="text-fuchsia-300/70">[{j + 1}]</span> {c.filePath}#L{c.startLine}-L{c.endLine}
                </button>
              ))}
            </div>
          )}
          {data.citations.map((c, j) =>
            expanded.has(j) && c.content ? (
              <div key={j} className="fade-in mt-2">
                <CodeBlock code={c.content} lang={c.language} />
              </div>
            ) : null
          )}

          <p className="mt-5 text-xs text-white/30">
            Generated by{" "}
            <a href="/" className="text-fuchsia-300/80 underline underline-offset-2 hover:text-fuchsia-300">
              RepoMind
            </a>{" "}
            — chat with any GitHub repository.
          </p>
        </div>
      )}
    </main>
  );
}
